"""add user profile fields

Revision ID: 430e052f3b87
Revises: 
Create Date: 2026-05-31 19:44:53.503061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430e052f3b87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('audio_file_path', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('audio_file_url', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('audio_generated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('target_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_language')
    op.drop_column('users', 'full_name')
    op.drop_column('stories', 'audio_generated')
    op.drop_column('stories', 'audio_file_url')
    op.drop_column('stories', 'audio_file_path')
    op.drop_column('stories', 'created_at')
    # ### end Alembic commands ###
